source 'https://rubygems.org'

require_relative '_plugins/ruby_4_compat'

# Jekyll 3 and Liquid require these libraries, which are no longer bundled
# with Ruby 3.4+.
gem 'csv'
gem 'bigdecimal'
gem 'webrick'

group :jekyll_plugins do
    gem 'github-pages'
    gem 'jekyll'
    gem 'jekyll-email-protect'
    gem 'jekyll-paginate-v2'
    gem 'jemoji'
    gem 'unicode_utils'
end
